version: '3'

services:
    db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      volumes:
       - ./mysql:/var/lib/mysql
      environment:
       - MYSQL_DATABASE=nodedb
       - MYSQL_ROOT_PASSWORD=root
      networks:
       - nodenet

    node:
      build:
        context: node
        dockerfile: ./Dockerfile.prod
      image: 1_2_fullcycle_node_js:prod
      container_name: node
      entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
      volumes:
       - ./node:/usr/src/app
      tty: true
      networks:
       - nodenet
      depends_on:
        - db
    
    nginx:
      build:
        context: ./nginx
        dockerfile: ./Dockerfile.prod
      image: 1_2_fullcycle_nginx:prod
      container_name: nginx
      networks:
       - nodenet
      ports:
       - "8080:80"
      depends_on:
       - node

networks:
  nodenet:
    driver: bridge